### ISSUE TITLE
Error: Cannot find module 'tunnel'

### ISSUE THREAD

**Issue by dominoma** [cardinalby/webext-buildtools-firefox-addons-action#6]
This error `Error: Cannot find module 'tunnel'` occurs when trying to execute the action

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'tunnel'
Require stack:
- /home/runner/work/_actions/cardinalby/webext-buildtools-firefox-addons-action/v1/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:[10](https://github.com/openvideo-streaming/extension/runs/6451547025?check_suite_focus=true#step:9:10)05:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.39669 (/home/runner/work/_actions/cardinalby/webext-buildtools-firefox-addons-action/v1/dist/index.js:121770:33)
    at __nccwpck_require__ (/home/runner/work/_actions/cardinalby/webext-buildtools-firefox-addons-action/v1/dist/index.js:122197:43)
    at Object.96255 (/home/runner/work/_actions/cardinalby/webext-buildtools-firefox-addons-action/v1/dist/index.js:[11](https://github.com/openvideo-streaming/extension/runs/6451547025?check_suite_focus=true#step:9:11)89:29)
    at __nccwpck_require__ (/home/runner/work/_actions/cardinalby/webext-buildtools-firefox-addons-action/v1/dist/index.js:[12](https://github.com/openvideo-streaming/extension/runs/6451547025?check_suite_focus=true#step:9:12)2[19](https://github.com/openvideo-streaming/extension/runs/6451547025?check_suite_focus=true#step:9:19)7:43)
    at Object.98041 (/home/runner/work/_actions/cardinalby/webext-buildtools-firefox-addons-action/v1/dist/index.js:657:23)
    at __nccwpck_require__ (/home/runner/work/_actions/cardinalby/webext-buildtools-firefox-addons-action/v1/dist/index.js:12[21](https://github.com/openvideo-streaming/extension/runs/6451547025?check_suite_focus=true#step:9:21)97:43) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/cardinalby/webext-buildtools-firefox-addons-action/v1/dist/index.js'
  ]
}
```

**Comment by cardinalby** [comment]
Hi, @dominoma and thanks for reporting!
I couldn't reproduce the exact error without additional information, but I updated the underlying library to work correctly with new Firefox Addons API v5, updated dependencies versions and added major tests. 

Please try again and let me know whether it works as expected

**Comment by dominoma** [comment]
Yes, now everything works. Thank you!
